id: ID1A4A421
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:47:46+00:00'
last_modified: '2022-06-07T13:58:13.445326+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30113
  title: གབ་པ་མངོན་འབྱུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D484:
      image_group_id: I1KG4036
      title: ''
      total_pages: 549
      order: 1
      base_file: D484.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
